
[functions.auto-submit-ms-forms]
enabled = true
verify_jwt = true
import_map = "./functions/auto-submit-ms-forms/deno.json"
entrypoint = "./functions/auto-submit-ms-forms/index.ts"

[functions.ms-forms-auto-worker]
enabled = true
verify_jwt = false
import_map = "./functions/ms-forms-auto-worker/deno.json"
entrypoint = "./functions/ms-forms-auto-worker/index.ts"
